dist:
  module: github.com/abicky/opentelemetry-collector-k8s-example/otelcol/cmd/otelcol
  name: otelcol
  output_path: ./build

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.135.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.135.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.135.0
  - gomod: go.opentelemetry.io/collector/processor/memorylimiterprocessor v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/processor/k8sattributesprocessor v0.135.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/filelogreceiver v0.135.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/receiver/prometheusreceiver v0.135.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.41.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.41.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.41.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.41.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.41.0
